/**
 * images.metadata.ts
 *
 * Human-maintained metadata for all photos.
 * metadataStatus: 'placeholder' = Petter needs to confirm/replace this entry.
 *
 * To add a new image:
 * 1. Run `npm run import-photos` to add it to images.generated.ts
 * 2. Add an entry here with the same slug
 */

import type { CollectionId, LocalizedString } from "@/types/content";

export interface PhotoMetadata {
  slug: string;
  collection: CollectionId;
  title: LocalizedString;
  location: LocalizedString;
  date: string; // ISO YYYY-MM-DD
  alt: LocalizedString;
  description?: LocalizedString;
  featuredOnHome: boolean;
  availableAsPrint: boolean;
  printSizes?: string[];
  wallMockup?: string;
  metadataStatus?: "placeholder" | "confirmed";
}

// TODO: Petter — please review all entries marked metadataStatus: 'placeholder'
// and replace title/location/date with the correct information.

export const photoMetadata: PhotoMetadata[] = [
  {
    slug: "african-buffalo",
    collection: "wildlife",
    title: { no: "Afrikansk bøffel", en: "African buffalo" },
    location: { no: "Masai Mara, Kenya", en: "Masai Mara, Kenya" },
    date: "2023-08-01",
    alt: { no: "Afrikansk bøffel i gresslette", en: "African buffalo on grassland" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "african-lion",
    collection: "wildlife",
    title: { no: "Afrikansk løve", en: "African lion" },
    location: { no: "Masai Mara, Kenya", en: "Masai Mara, Kenya" },
    date: "2023-08-03",
    alt: { no: "Afrikansk løve i naturen", en: "African lion in the wild" },
    featuredOnHome: true,
    availableAsPrint: true,
    printSizes: ["30x40", "50x70", "70x100"],
    metadataStatus: "placeholder",
  },
  {
    slug: "atlantic-puffin",
    collection: "wildlife",
    title: { no: "Lunde", en: "Atlantic puffin" },
    location: { no: "Runde, Møre og Romsdal", en: "Runde, Møre og Romsdal" },
    date: "2023-05-15",
    alt: { no: "Lunde med fisk i nebbet", en: "Atlantic puffin with fish in beak" },
    featuredOnHome: true,
    availableAsPrint: true,
    printSizes: ["30x40", "50x70", "70x100"],
    metadataStatus: "placeholder",
  },
  {
    slug: "blue-tit",
    collection: "wildlife",
    title: { no: "Blåmeis", en: "Blue tit" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-02-10",
    alt: { no: "Blåmeis på en gren", en: "Blue tit on a branch" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "blue-tit-1",
    collection: "wildlife",
    title: { no: "Blåmeis II", en: "Blue tit II" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-02-11",
    alt: { no: "Blåmeis i vinterlandskap", en: "Blue tit in winter landscape" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "brambling",
    collection: "wildlife",
    title: { no: "Bjørkefink", en: "Brambling" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-03-05",
    alt: { no: "Bjørkefink i naturlig habitat", en: "Brambling in natural habitat" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "chaffinch",
    collection: "wildlife",
    title: { no: "Bokfink", en: "Chaffinch" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-04-20",
    alt: { no: "Bokfink på gren", en: "Chaffinch on branch" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "chaffinch-2",
    collection: "wildlife",
    title: { no: "Bokfink II", en: "Chaffinch II" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-04-21",
    alt: { no: "Bokfink i nærbilde", en: "Chaffinch close-up" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "coal-tit",
    collection: "wildlife",
    title: { no: "Svartmeis", en: "Coal tit" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-01-15",
    alt: { no: "Svartmeis i vinterskogen", en: "Coal tit in winter forest" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "common-goldeneye",
    collection: "wildlife",
    title: { no: "Kvinand", en: "Common goldeneye" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-04-08",
    alt: { no: "Kvinand på vann", en: "Common goldeneye on water" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "eurasian-bullfinch",
    collection: "wildlife",
    title: { no: "Dompap", en: "Eurasian bullfinch" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-12-20",
    alt: { no: "Hanndom på snødekket gren", en: "Male bullfinch on snow-covered branch" },
    featuredOnHome: true,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "fieldfare",
    collection: "wildlife",
    title: { no: "Gråtrost", en: "Fieldfare" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-10-12",
    alt: { no: "Gråtrost i høstlandskap", en: "Fieldfare in autumn landscape" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "golden-plover",
    collection: "wildlife",
    title: { no: "Heilo", en: "Golden plover" },
    location: { no: "Hardangervidda, Norge", en: "Hardangervidda, Norway" },
    date: "2023-07-10",
    alt: { no: "Heilo på fjellet", en: "Golden plover on the mountain plateau" },
    featuredOnHome: true,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "great-tit",
    collection: "wildlife",
    title: { no: "Kjøttmeis", en: "Great tit" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-02-28",
    alt: { no: "Kjøttmeis på fuglebar", en: "Great tit on bird feeder" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "house-sparrow",
    collection: "wildlife",
    title: { no: "Gråspurv", en: "House sparrow" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-03-22",
    alt: { no: "Gråspurv i naturlig omgivelse", en: "House sparrow in natural setting" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "mallard",
    collection: "wildlife",
    title: { no: "Stokkand", en: "Mallard" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-04-02",
    alt: { no: "Hannand stokkand", en: "Male mallard duck" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "northern-wheatear-1",
    collection: "wildlife",
    title: { no: "Steinskvett", en: "Northern wheatear" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-05-28",
    alt: { no: "Steinskvett på steinblokk", en: "Northern wheatear on a rock" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "norwegian-white-sheep",
    collection: "wildlife",
    title: { no: "Norsk kvit sau", en: "Norwegian white sheep" },
    location: { no: "Vestlandet, Norge", en: "Western Norway" },
    date: "2023-07-20",
    alt: { no: "Norsk hvit sau i fjellandskap", en: "Norwegian white sheep in mountain landscape" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "red-squirrel",
    collection: "wildlife",
    title: { no: "Ekorn", en: "Red squirrel" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-09-15",
    alt: { no: "Ekorn i skogen", en: "Red squirrel in the forest" },
    featuredOnHome: true,
    availableAsPrint: true,
    printSizes: ["30x40", "50x70", "70x100"],
    metadataStatus: "placeholder",
  },
  {
    slug: "red-squirrel-1",
    collection: "wildlife",
    title: { no: "Ekorn II", en: "Red squirrel II" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-09-15",
    alt: { no: "Ekorn med nøtt", en: "Red squirrel with nut" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "red-squirrel-2",
    collection: "wildlife",
    title: { no: "Ekorn III", en: "Red squirrel III" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-09-16",
    alt: { no: "Ekorn i hopp", en: "Red squirrel mid-jump" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "red-squirrel-3",
    collection: "wildlife",
    title: { no: "Ekorn IV", en: "Red squirrel IV" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-09-16",
    alt: { no: "Ekorn nærbilde", en: "Red squirrel close-up" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "red-squirrel-4",
    collection: "wildlife",
    title: { no: "Ekorn V", en: "Red squirrel V" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-09-17",
    alt: { no: "Ekorn på trestamme", en: "Red squirrel on tree trunk" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "scandinavian-red-fox",
    collection: "wildlife",
    title: { no: "Skandinavisk rødrev", en: "Scandinavian red fox" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-11-08",
    alt: { no: "Rødrev i vinterlandskap", en: "Red fox in winter landscape" },
    featuredOnHome: true,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
  {
    slug: "white-wagtail",
    collection: "wildlife",
    title: { no: "Linerle", en: "White wagtail" },
    location: { no: "Norge", en: "Norway" },
    date: "2023-05-05",
    alt: { no: "Linerle ved vann", en: "White wagtail near water" },
    featuredOnHome: false,
    availableAsPrint: false,
    metadataStatus: "placeholder",
  },
];
