/**
 * images.metadata.ts
 *
 * AUTO-GENERATED from ~/Desktop/wildlife-id/work/manifest.csv via scripts/importPhotos.ts.
 * Hand-edits to title/location can be made here, but will be overwritten if the importer is re-run.
 * Re-run: npm run import-photos
 */

import type { CollectionId, LocalizedString } from "@/types/content";

export interface PhotoMetadata {
  slug: string;
  collection: CollectionId;
  title: LocalizedString;
  latinName?: string;
  location: LocalizedString;
  date: string;
  camera?: string;
  lens?: string;
  alt: LocalizedString;
  description?: LocalizedString;
  featuredOnHome: boolean;
  availableAsPrint: boolean;
  printSizes?: string[];
  wallMockup?: string;
  metadataStatus?: "placeholder" | "confirmed";
  confidence?: "low" | "medium" | "high";
}

export const photoMetadata: PhotoMetadata[] = [
  { slug: "roe-deer-01", collection: "wildlife", title: { no: "Rådyr", en: "Roe Deer" }, latinName: "Capreolus capreolus", location: { no: "", en: "" }, date: "2025-06-11", alt: { no: "Rådyr i naturen", en: "Roe Deer in the wild" }, featuredOnHome: true, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "european-golden-plover-01", collection: "wildlife", title: { no: "Heilo", en: "European Golden Plover" }, latinName: "Pluvialis apricaria", location: { no: "", en: "" }, date: "2025-06-12", alt: { no: "Heilo i naturen", en: "European Golden Plover in the wild" }, featuredOnHome: true, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "european-golden-plover-02", collection: "wildlife", title: { no: "Heilo", en: "European Golden Plover" }, latinName: "Pluvialis apricaria", location: { no: "", en: "" }, date: "2025-06-12", alt: { no: "Heilo i naturen", en: "European Golden Plover in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "white-wagtail-01", collection: "wildlife", title: { no: "Linerle", en: "White Wagtail" }, latinName: "Motacilla alba", location: { no: "", en: "" }, date: "2025-06-12", alt: { no: "Linerle i naturen", en: "White Wagtail in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "medium" },
  { slug: "domestic-sheep-01", collection: "wildlife", title: { no: "Sau", en: "Domestic Sheep" }, latinName: "Ovis aries", location: { no: "", en: "" }, date: "2025-06-13", alt: { no: "Sau i naturen", en: "Domestic Sheep in the wild" }, featuredOnHome: true, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "domestic-sheep-02", collection: "wildlife", title: { no: "Sau", en: "Domestic Sheep" }, latinName: "Ovis aries", location: { no: "", en: "" }, date: "2025-06-13", alt: { no: "Sau i naturen", en: "Domestic Sheep in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "domestic-sheep-03", collection: "wildlife", title: { no: "Sau", en: "Domestic Sheep" }, latinName: "Ovis aries", location: { no: "", en: "" }, date: "2025-06-13", alt: { no: "Sau i naturen", en: "Domestic Sheep in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "common-chaffinch-01", collection: "wildlife", title: { no: "Bokfink", en: "Common Chaffinch" }, latinName: "Fringilla coelebs", location: { no: "", en: "" }, date: "2020-06-04", alt: { no: "Bokfink i naturen", en: "Common Chaffinch in the wild" }, featuredOnHome: true, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-bullfinch-01", collection: "wildlife", title: { no: "Dompap", en: "Eurasian Bullfinch" }, latinName: "Pyrrhula pyrrhula", location: { no: "", en: "" }, date: "2022-02-21", alt: { no: "Dompap i naturen", en: "Eurasian Bullfinch in the wild" }, featuredOnHome: true, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-01", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2022-03-14", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: true, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "grey-heron-01", collection: "wildlife", title: { no: "Gråhegre", en: "Grey Heron" }, latinName: "Ardea cinerea", location: { no: "", en: "" }, date: "2022-03-18", alt: { no: "Gråhegre i naturen", en: "Grey Heron in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-02", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2022-03-19", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-03", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2022-03-19", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-blue-tit-01", collection: "wildlife", title: { no: "Blåmeis", en: "Eurasian Blue Tit" }, latinName: "Cyanistes caeruleus", location: { no: "", en: "" }, date: "2022-03-19", alt: { no: "Blåmeis i naturen", en: "Eurasian Blue Tit in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-nuthatch-01", collection: "wildlife", title: { no: "Spettmeis", en: "Eurasian Nuthatch" }, latinName: "Sitta europaea", location: { no: "", en: "" }, date: "2021-07-01", alt: { no: "Spettmeis i naturen", en: "Eurasian Nuthatch in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-blue-tit-02", collection: "wildlife", title: { no: "Blåmeis", en: "Eurasian Blue Tit" }, latinName: "Cyanistes caeruleus", location: { no: "", en: "" }, date: "2022-06-06", alt: { no: "Blåmeis i naturen", en: "Eurasian Blue Tit in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "wood-sandpiper-01", collection: "wildlife", title: { no: "Grønnstilk", en: "Wood Sandpiper" }, latinName: "Tringa glareola", location: { no: "", en: "" }, date: "2022-06-06", alt: { no: "Grønnstilk i naturen", en: "Wood Sandpiper in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "common-kestrel-01", collection: "wildlife", title: { no: "Tårnfalk", en: "Common Kestrel" }, latinName: "Falco tinnunculus", location: { no: "", en: "" }, date: "2021-07-01", alt: { no: "Tårnfalk i naturen", en: "Common Kestrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "bluethroat-01", collection: "wildlife", title: { no: "Blåstrupe", en: "Bluethroat" }, latinName: "Luscinia svecica", location: { no: "", en: "" }, date: "2021-07-01", alt: { no: "Blåstrupe i naturen", en: "Bluethroat in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "stoat-01", collection: "wildlife", title: { no: "Røyskatt", en: "Stoat" }, latinName: "Mustela erminea", location: { no: "", en: "" }, date: "2023-05-20", alt: { no: "Røyskatt i naturen", en: "Stoat in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "stoat-02", collection: "wildlife", title: { no: "Røyskatt", en: "Stoat" }, latinName: "Mustela erminea", location: { no: "", en: "" }, date: "2023-05-20", alt: { no: "Røyskatt i naturen", en: "Stoat in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "stoat-03", collection: "wildlife", title: { no: "Røyskatt", en: "Stoat" }, latinName: "Mustela erminea", location: { no: "", en: "" }, date: "2023-05-20", alt: { no: "Røyskatt i naturen", en: "Stoat in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "red-breasted-nuthatch-01", collection: "wildlife", title: { no: "Kanadaspettmeis", en: "Red-breasted Nuthatch" }, latinName: "Sitta canadensis", location: { no: "", en: "" }, date: "2021-07-02", alt: { no: "Kanadaspettmeis i naturen", en: "Red-breasted Nuthatch in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "medium" },
  { slug: "white-wagtail-02", collection: "wildlife", title: { no: "Linerle", en: "White Wagtail" }, latinName: "Motacilla alba", location: { no: "", en: "" }, date: "2023-06-08", alt: { no: "Linerle i naturen", en: "White Wagtail in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "white-throated-dipper-01", collection: "wildlife", title: { no: "Fossekall", en: "White-throated Dipper" }, latinName: "Cinclus cinclus", location: { no: "", en: "" }, date: "2023-06-08", alt: { no: "Fossekall i naturen", en: "White-throated Dipper in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "common-sandpiper-01", collection: "wildlife", title: { no: "Strandsnipe", en: "Common Sandpiper" }, latinName: "Actitis hypoleucos", location: { no: "", en: "" }, date: "2023-06-10", alt: { no: "Strandsnipe i naturen", en: "Common Sandpiper in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "great-skua-01", collection: "wildlife", title: { no: "Storjo", en: "Great Skua" }, latinName: "Stercorarius skua", location: { no: "", en: "" }, date: "2023-06-10", alt: { no: "Storjo i naturen", en: "Great Skua in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "atlantic-puffin-01", collection: "wildlife", title: { no: "Lunde", en: "Atlantic Puffin" }, latinName: "Fratercula arctica", location: { no: "", en: "" }, date: "2023-06-10", alt: { no: "Lunde i naturen", en: "Atlantic Puffin in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "house-sparrow-fledgling-01", collection: "wildlife", title: { no: "Gråspurv", en: "House Sparrow (fledgling)" }, latinName: "Passer domesticus", location: { no: "", en: "" }, date: "2021-07-09", alt: { no: "Gråspurv i naturen", en: "House Sparrow (fledgling) in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "medium" },
  { slug: "mallard-01", collection: "wildlife", title: { no: "Stokkand", en: "Mallard" }, latinName: "Anas platyrhynchos", location: { no: "", en: "" }, date: "2021-07-09", alt: { no: "Stokkand i naturen", en: "Mallard in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "western-yellow-wagtail-01", collection: "wildlife", title: { no: "Gulerle", en: "Western Yellow Wagtail" }, latinName: "Motacilla flava", location: { no: "", en: "" }, date: "2021-07-12", alt: { no: "Gulerle i naturen", en: "Western Yellow Wagtail in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "grey-wagtail-01", collection: "wildlife", title: { no: "Vintererle", en: "Grey Wagtail" }, latinName: "Motacilla cinerea", location: { no: "", en: "" }, date: "2021-07-12", alt: { no: "Vintererle i naturen", en: "Grey Wagtail in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "grey-wagtail-02", collection: "wildlife", title: { no: "Vintererle", en: "Grey Wagtail" }, latinName: "Motacilla cinerea", location: { no: "", en: "" }, date: "2021-07-12", alt: { no: "Vintererle i naturen", en: "Grey Wagtail in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "medium" },
  { slug: "grey-wagtail-03", collection: "wildlife", title: { no: "Vintererle", en: "Grey Wagtail" }, latinName: "Motacilla cinerea", location: { no: "", en: "" }, date: "2021-07-12", alt: { no: "Vintererle i naturen", en: "Grey Wagtail in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "white-wagtail-03", collection: "wildlife", title: { no: "Linerle", en: "White Wagtail" }, latinName: "Motacilla alba", location: { no: "", en: "" }, date: "2021-07-14", alt: { no: "Linerle i naturen", en: "White Wagtail in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-04", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-07-17", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "common-crane-01", collection: "wildlife", title: { no: "Trane", en: "Common Crane" }, latinName: "Grus grus", location: { no: "", en: "" }, date: "2021-07-17", alt: { no: "Trane i naturen", en: "Common Crane in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "great-skua-02", collection: "wildlife", title: { no: "Storjo", en: "Great Skua" }, latinName: "Stercorarius skua", location: { no: "", en: "" }, date: "2021-07-21", alt: { no: "Storjo i naturen", en: "Great Skua in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "medium" },
  { slug: "atlantic-puffin-02", collection: "wildlife", title: { no: "Lunde", en: "Atlantic Puffin" }, latinName: "Fratercula arctica", location: { no: "", en: "" }, date: "2021-07-21", alt: { no: "Lunde i naturen", en: "Atlantic Puffin in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "atlantic-puffin-03", collection: "wildlife", title: { no: "Lunde", en: "Atlantic Puffin" }, latinName: "Fratercula arctica", location: { no: "", en: "" }, date: "2021-07-21", alt: { no: "Lunde i naturen", en: "Atlantic Puffin in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "atlantic-puffin-04", collection: "wildlife", title: { no: "Lunde", en: "Atlantic Puffin" }, latinName: "Fratercula arctica", location: { no: "", en: "" }, date: "2021-07-21", alt: { no: "Lunde i naturen", en: "Atlantic Puffin in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "common-sandpiper-02", collection: "wildlife", title: { no: "Strandsnipe", en: "Common Sandpiper" }, latinName: "Actitis hypoleucos", location: { no: "", en: "" }, date: "2021-07-22", alt: { no: "Strandsnipe i naturen", en: "Common Sandpiper in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-05", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2022-06-09", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-jackdaw-01", collection: "wildlife", title: { no: "Kaie", en: "Eurasian Jackdaw" }, latinName: "Corvus monedula", location: { no: "", en: "" }, date: "2022-06-09", alt: { no: "Kaie i naturen", en: "Eurasian Jackdaw in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-06", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2022-06-09", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "great-spotted-woodpecker-01", collection: "wildlife", title: { no: "Flaggspett", en: "Great Spotted Woodpecker" }, latinName: "Dendrocopos major", location: { no: "", en: "" }, date: "2022-06-09", alt: { no: "Flaggspett i naturen", en: "Great Spotted Woodpecker in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-nuthatch-02", collection: "wildlife", title: { no: "Spettmeis", en: "Eurasian Nuthatch" }, latinName: "Sitta europaea", location: { no: "", en: "" }, date: "2021-07-26", alt: { no: "Spettmeis i naturen", en: "Eurasian Nuthatch in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "great-spotted-woodpecker-02", collection: "wildlife", title: { no: "Flaggspett", en: "Great Spotted Woodpecker" }, latinName: "Dendrocopos major", location: { no: "", en: "" }, date: "2022-06-10", alt: { no: "Flaggspett i naturen", en: "Great Spotted Woodpecker in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "great-spotted-woodpecker-03", collection: "wildlife", title: { no: "Flaggspett", en: "Great Spotted Woodpecker" }, latinName: "Dendrocopos major", location: { no: "", en: "" }, date: "2022-06-10", alt: { no: "Flaggspett i naturen", en: "Great Spotted Woodpecker in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "african-buffalo-01", collection: "wildlife", title: { no: "Afrikansk bøffel", en: "African Buffalo" }, latinName: "Syncerus caffer", location: { no: "", en: "" }, date: "2022-06-25", alt: { no: "Afrikansk bøffel i naturen", en: "African Buffalo in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "african-buffalo-02", collection: "wildlife", title: { no: "Afrikansk bøffel", en: "African Buffalo" }, latinName: "Syncerus caffer", location: { no: "", en: "" }, date: "2022-06-25", alt: { no: "Afrikansk bøffel i naturen", en: "African Buffalo in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "cheetah-01", collection: "wildlife", title: { no: "Gepard", en: "Cheetah" }, latinName: "Acinonyx jubatus", location: { no: "", en: "" }, date: "2022-06-25", alt: { no: "Gepard i naturen", en: "Cheetah in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "cheetah-02", collection: "wildlife", title: { no: "Gepard", en: "Cheetah" }, latinName: "Acinonyx jubatus", location: { no: "", en: "" }, date: "2022-06-25", alt: { no: "Gepard i naturen", en: "Cheetah in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "spotted-hyena-01", collection: "wildlife", title: { no: "Flekkhyene", en: "Spotted Hyena" }, latinName: "Crocuta crocuta", location: { no: "", en: "" }, date: "2022-06-25", alt: { no: "Flekkhyene i naturen", en: "Spotted Hyena in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "lion-01", collection: "wildlife", title: { no: "Løve", en: "Lion" }, latinName: "Panthera leo", location: { no: "", en: "" }, date: "2022-06-25", alt: { no: "Løve i naturen", en: "Lion in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "lion-02", collection: "wildlife", title: { no: "Løve", en: "Lion" }, latinName: "Panthera leo", location: { no: "", en: "" }, date: "2022-06-25", alt: { no: "Løve i naturen", en: "Lion in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "european-golden-plover-03", collection: "wildlife", title: { no: "Heilo", en: "European Golden Plover" }, latinName: "Pluvialis apricaria", location: { no: "", en: "" }, date: "2021-07-26", alt: { no: "Heilo i naturen", en: "European Golden Plover in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "european-golden-plover-04", collection: "wildlife", title: { no: "Heilo", en: "European Golden Plover" }, latinName: "Pluvialis apricaria", location: { no: "", en: "" }, date: "2021-07-26", alt: { no: "Heilo i naturen", en: "European Golden Plover in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "lion-03", collection: "wildlife", title: { no: "Løve", en: "Lion" }, latinName: "Panthera leo", location: { no: "", en: "" }, date: "2022-06-25", alt: { no: "Løve i naturen", en: "Lion in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "lion-04", collection: "wildlife", title: { no: "Løve", en: "Lion" }, latinName: "Panthera leo", location: { no: "", en: "" }, date: "2022-06-25", alt: { no: "Løve i naturen", en: "Lion in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-07", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-07-27", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "african-bush-elephant-01", collection: "wildlife", title: { no: "Afrikansk savanneelefant", en: "African Bush Elephant" }, latinName: "Loxodonta africana", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Afrikansk savanneelefant i naturen", en: "African Bush Elephant in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "spotted-flycatcher-01", collection: "wildlife", title: { no: "Gråfluesnapper", en: "Spotted Flycatcher" }, latinName: "Muscicapa striata", location: { no: "", en: "" }, date: "2021-08-04", alt: { no: "Gråfluesnapper i naturen", en: "Spotted Flycatcher in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "blue-gray-gnatcatcher-01", collection: "wildlife", title: { no: "Blågrå myggsanger", en: "Blue-gray Gnatcatcher" }, latinName: "Polioptila caerulea", location: { no: "", en: "" }, date: "2021-08-04", alt: { no: "Blågrå myggsanger i naturen", en: "Blue-gray Gnatcatcher in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "chacma-baboon-01", collection: "wildlife", title: { no: "Chakmababuin", en: "Chacma Baboon" }, latinName: "Papio ursinus", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Chakmababuin i naturen", en: "Chacma Baboon in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "common-hippopotamus-01", collection: "wildlife", title: { no: "Flodhest", en: "Common Hippopotamus" }, latinName: "Hippopotamus amphibius", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Flodhest i naturen", en: "Common Hippopotamus in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "lion-05", collection: "wildlife", title: { no: "Løve (hunn)", en: "Lion" }, latinName: "Panthera leo", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Løve (hunn) i naturen", en: "Lion in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "lion-06", collection: "wildlife", title: { no: "Løve (hunn)", en: "Lion" }, latinName: "Panthera leo", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Løve (hunn) i naturen", en: "Lion in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "lion-07", collection: "wildlife", title: { no: "Løve (hunn)", en: "Lion" }, latinName: "Panthera leo", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Løve (hunn) i naturen", en: "Lion in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "masai-giraffe-01", collection: "wildlife", title: { no: "Masaisjiraff", en: "Masai Giraffe" }, latinName: "Giraffa camelopardalis tippelskirchi", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Masaisjiraff i naturen", en: "Masai Giraffe in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "masai-giraffe-02", collection: "wildlife", title: { no: "Masaisjiraff", en: "Masai Giraffe" }, latinName: "Giraffa camelopardalis tippelskirchi", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Masaisjiraff i naturen", en: "Masai Giraffe in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "masai-giraffe-03", collection: "wildlife", title: { no: "Masaisjiraff", en: "Masai Giraffe" }, latinName: "Giraffa camelopardalis tippelskirchi", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Masaisjiraff i naturen", en: "Masai Giraffe in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "topi-01", collection: "wildlife", title: { no: "Topi", en: "Topi" }, latinName: "Damaliscus lunatus jimela", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Topi i naturen", en: "Topi in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "african-bush-elephant-02", collection: "wildlife", title: { no: "Afrikansk savanneelefant", en: "African Bush Elephant" }, latinName: "Loxodonta africana", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Afrikansk savanneelefant i naturen", en: "African Bush Elephant in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "blue-wildebeest-01", collection: "wildlife", title: { no: "Blå gnu", en: "Blue Wildebeest" }, latinName: "Connochaetes taurinus", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Blå gnu i naturen", en: "Blue Wildebeest in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "spotted-hyena-02", collection: "wildlife", title: { no: "Flekkhyene", en: "Spotted Hyena" }, latinName: "Crocuta crocuta", location: { no: "", en: "" }, date: "2022-06-26", alt: { no: "Flekkhyene i naturen", en: "Spotted Hyena in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-08", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-12-30", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "egyptian-goose-01", collection: "wildlife", title: { no: "Nilgås", en: "Egyptian Goose" }, latinName: "Alopochen aegyptiaca", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Nilgås i naturen", en: "Egyptian Goose in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-09", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-12-30", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "great-white-pelican-01", collection: "wildlife", title: { no: "Rosenpelikan", en: "Great White Pelican" }, latinName: "Pelecanus onocrotalus", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Rosenpelikan i naturen", en: "Great White Pelican in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "egyptian-goose-02", collection: "wildlife", title: { no: "Nilgås", en: "Egyptian Goose" }, latinName: "Alopochen aegyptiaca", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Nilgås i naturen", en: "Egyptian Goose in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "great-white-pelican-02", collection: "wildlife", title: { no: "Rosenpelikan", en: "Great White Pelican" }, latinName: "Phalacrocorax lucidus", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Rosenpelikan i naturen", en: "Great White Pelican in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "spot-billed-pelican-01", collection: "wildlife", title: { no: "Gråpelikan", en: "Spot-billed Pelican" }, latinName: "Pelecanus philippensis", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Gråpelikan i naturen", en: "Spot-billed Pelican in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "medium" },
  { slug: "spot-billed-pelican-02", collection: "wildlife", title: { no: "Gråpelikan", en: "Spot-billed Pelican" }, latinName: "Pelecanus philippensis", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Gråpelikan i naturen", en: "Spot-billed Pelican in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "medium" },
  { slug: "eurasian-red-squirrel-10", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-12-30", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-11", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-12-30", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-12", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-12-30", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-13", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-12-30", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-14", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-12-30", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-15", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-12-30", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-16", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-12-30", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "great-egret-01", collection: "wildlife", title: { no: "Egretthegre", en: "Great Egret" }, latinName: "Ardea alba", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Egretthegre i naturen", en: "Great Egret in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "yellow-billed-stork-01", collection: "wildlife", title: { no: "Gulnebbstork", en: "Yellow-billed Stork" }, latinName: "Mycteria ibis", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Gulnebbstork i naturen", en: "Yellow-billed Stork in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "goliath-heron-01", collection: "wildlife", title: { no: "Goliatthegre", en: "Goliath Heron" }, latinName: "Ardea goliath", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Goliatthegre i naturen", en: "Goliath Heron in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "pied-kingfisher-01", collection: "wildlife", title: { no: "Broget isfugl", en: "Pied Kingfisher" }, latinName: "Ceryle rudis", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Broget isfugl i naturen", en: "Pied Kingfisher in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "grey-heron-02", collection: "wildlife", title: { no: "Gråhegre", en: "Grey Heron" }, latinName: "Ardea cinerea", location: { no: "", en: "" }, date: "2022-06-27", alt: { no: "Gråhegre i naturen", en: "Grey Heron in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "atlantic-puffin-05", collection: "wildlife", title: { no: "Lunde", en: "Atlantic Puffin" }, latinName: "Fratercula arctica", location: { no: "", en: "" }, date: "2022-07-12", alt: { no: "Lunde i naturen", en: "Atlantic Puffin in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "atlantic-puffin-06", collection: "wildlife", title: { no: "Lunde", en: "Atlantic Puffin" }, latinName: "Fratercula arctica", location: { no: "", en: "" }, date: "2022-07-12", alt: { no: "Lunde i naturen", en: "Atlantic Puffin in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "great-tit-01", collection: "wildlife", title: { no: "Kjøttmeis", en: "Great Tit" }, latinName: "Parus major", location: { no: "", en: "" }, date: "2020-06-13", alt: { no: "Kjøttmeis i naturen", en: "Great Tit in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "pied-wagtail-01", collection: "wildlife", title: { no: "Svartryggerle", en: "Pied Wagtail" }, latinName: "Motacilla alba yarrellii", location: { no: "", en: "" }, date: "2020-06-15", alt: { no: "Svartryggerle i naturen", en: "Pied Wagtail in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-blue-tit-03", collection: "wildlife", title: { no: "Blåmeis", en: "Eurasian Blue Tit" }, latinName: "Cyanistes caeruleus", location: { no: "", en: "" }, date: "2021-04-17", alt: { no: "Blåmeis i naturen", en: "Eurasian Blue Tit in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "common-chaffinch-02", collection: "wildlife", title: { no: "Bokfink", en: "Common Chaffinch" }, latinName: "Fringilla coelebs", location: { no: "", en: "" }, date: "2021-04-19", alt: { no: "Bokfink i naturen", en: "Common Chaffinch in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "common-chaffinch-03", collection: "wildlife", title: { no: "Bokfink", en: "Common Chaffinch" }, latinName: "Fringilla coelebs", location: { no: "", en: "" }, date: "2021-04-19", alt: { no: "Bokfink i naturen", en: "Common Chaffinch in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-17", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-05-02", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "eurasian-red-squirrel-18", collection: "wildlife", title: { no: "Ekorn", en: "Eurasian Red Squirrel" }, latinName: "Sciurus vulgaris", location: { no: "", en: "" }, date: "2021-05-02", alt: { no: "Ekorn i naturen", en: "Eurasian Red Squirrel in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "common-goldeneye-01", collection: "wildlife", title: { no: "Kvinand", en: "Common Goldeneye" }, latinName: "Bucephala clangula", location: { no: "", en: "" }, date: "2021-05-11", alt: { no: "Kvinand i naturen", en: "Common Goldeneye in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "great-tit-02", collection: "wildlife", title: { no: "Kjøttmeis", en: "Great Tit" }, latinName: "Parus major", location: { no: "", en: "" }, date: "2021-05-14", alt: { no: "Kjøttmeis i naturen", en: "Great Tit in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "european-starling-01", collection: "wildlife", title: { no: "Stær", en: "European Starling" }, latinName: "Sturnus vulgaris", location: { no: "", en: "" }, date: "2021-05-16", alt: { no: "Stær i naturen", en: "European Starling in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "common-goldeneye-02", collection: "wildlife", title: { no: "Kvinand", en: "Common Goldeneye" }, latinName: "Bucephala clangula", location: { no: "", en: "" }, date: "2021-04-24", alt: { no: "Kvinand i naturen", en: "Common Goldeneye in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
  { slug: "mallard-02", collection: "wildlife", title: { no: "Stokkand", en: "Mallard" }, latinName: "Anas platyrhynchos", location: { no: "", en: "" }, date: "2021-04-24", alt: { no: "Stokkand i naturen", en: "Mallard in the wild" }, featuredOnHome: false, availableAsPrint: false, metadataStatus: "placeholder", confidence: "high" },
];
