/**
 * importPhotos.ts
 *
 * One-time script to:
 * 1. Read all folders in "Animal photos/" (Wildlife collection source)
 * 2. Copy each image to /public/images/photos/wildlife/[slug].jpg
 * 3. Read dimensions via sharp
 * 4. Generate blur placeholder via plaiceholder
 * 5. Write content/images.generated.ts
 *
 * Run: npm run import-photos
 * Requires: sharp, plaiceholder, tsx installed
 */

import fs from "fs";
import path from "path";
import { getPlaiceholder } from "plaiceholder";

const SOURCE_DIR = path.resolve(process.cwd(), "Animal photos");
const DEST_DIR = path.resolve(process.cwd(), "public/images/photos/wildlife");
const OUTPUT_FILE = path.resolve(process.cwd(), "content/images.generated.ts");

interface GeneratedImage {
  slug: string;
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
}

async function run() {
  if (!fs.existsSync(SOURCE_DIR)) {
    console.error(`Source directory not found: ${SOURCE_DIR}`);
    process.exit(1);
  }

  fs.mkdirSync(DEST_DIR, { recursive: true });

  const slugFolders = fs
    .readdirSync(SOURCE_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const results: GeneratedImage[] = [];

  for (const slug of slugFolders) {
    const folderPath = path.join(SOURCE_DIR, slug);
    const files = fs.readdirSync(folderPath).filter((f) => /\.(jpg|jpeg|png|webp|avif)$/i.test(f));

    if (files.length === 0) {
      console.warn(`  [skip] ${slug} — no image files found`);
      continue;
    }

    const srcFile = path.join(folderPath, files[0]!);
    const destFile = path.join(DEST_DIR, `${slug}.jpg`);

    // Copy file
    fs.copyFileSync(srcFile, destFile);
    console.log(`  [copy] ${slug}`);

    // Get dimensions + blur via plaiceholder
    const buffer = fs.readFileSync(destFile);
    const { base64, metadata } = await getPlaiceholder(buffer, { size: 10 });

    results.push({
      slug,
      src: `/images/photos/wildlife/${slug}.jpg`,
      width: metadata.width ?? 1200,
      height: metadata.height ?? 800,
      blurDataURL: base64,
    });
  }

  // Write generated file
  const lines = [
    "// AUTO-GENERATED by scripts/importPhotos.ts — do not edit manually",
    "// Re-run: npm run import-photos",
    "",
    "export interface GeneratedImageData {",
    "  slug: string;",
    "  src: string;",
    "  width: number;",
    "  height: number;",
    "  blurDataURL: string;",
    "}",
    "",
    "export const generatedImages: GeneratedImageData[] = [",
    ...results.map(
      (r) =>
        `  { slug: "${r.slug}", src: "${r.src}", width: ${r.width}, height: ${r.height}, blurDataURL: "${r.blurDataURL}" },`,
    ),
    "];",
    "",
  ];

  fs.writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");
  console.log(`\nWrote ${results.length} images to ${OUTPUT_FILE}`);
}

run().catch(console.error);
